### PR TITLE
Remove ICLA.md

### PR DESCRIPTION
**Pull request by orbea**
Hi,

I think your recent choices of changing redream development to a proprietary format are rather unfortunate and it would be really good if you reconsidered. I think there are two reasons why you have not seen many outside contributions.

1. To be blunt this CLA agreement is inane and the thing it does best is deter people from contributing.
2. This is more technical, the lack of save states make using debugging tools like apitrace impractical. I would of spent significant time helping with debugging and testing issues once this essential feature was implemented... However without a free code base I can never do this.

Personally I had hoped to make a good redream build script for slackbuilds.org so Slackware users could enjoy either the stand alone version or libretro core with standard system tools. However this CLA agreement is and was concerning so I decided to wait until I was assured you would not pull the rug out on everyone, unfortunately my suspicions turned out to be true...

So please remove this file and start publicly contributing to redream with a free license again so other people can work with you!

### CODE REVIEW

**Comment by inolen** [comment]
Given that the CLA is only ~7 months old, I'm not sure your reasoning has legs.

You're more than welcome to your viewpoint on CLAs, sorry it doesn't sit well with you.

**Comment by orbea** [comment]
I'm sorry it turned out this way and I hoped better from you. Instead you are just shooting yourself in the foot. Can't you see that you are just making it impossible for anyone to work with you and destroying the usefulness of redream? As it stands redream's only hope is that someone can carry on without you... This self sabotage is quite disheartening.

**Comment by inolen** [comment]
I wish you would be respectful of developer's decisions.

redream is doing fine.

**Comment by bor-real** [comment]
There is no respect for a developer who only has green in his eyes.

**Pull request closed without merging**
