### PR TITLE
Libretro static Makefile

### PR DESCRIPTION
**Pull request by twinaphex**
@inolen This should make the shallow fork hosted at libretro organization completely unnecessary so that we can remove it. I will offer to maintain this static Makefile too in case you feel it's a maintenance burden.

Note: I had to add some defines like HAVE_IMGUI/HAVE_DEBUGGER. You will have to define these for your non-libretro standalone builds in case you want to use the imgui interface and/or the debugger. It might be possible to use these with the libretro port too, but the static Makefile target has them baked out for now.

Hopefully I did not introduce any mistakes.

### CODE REVIEW

**Comment by inolen** [comment]
Note, there is already HAVE_IMGUI / HAVE_MICROPROFILE in master. I just stubbed out the implementation of the functions vs the call sites.

**Comment by twinaphex** [comment]
Ah OK. That's good to hear.

**Comment by twinaphex** [comment]
I can try baking that in then without adding all the invasive ifdefs.

**Comment by inolen** [comment]
Don't sweat it, i'll get this merged tonight.

**Comment by twinaphex** [comment]
Alright, so I should leave it to you and you will just base the commits on this PR sans the ifdefs in the source files? Sounds good to me.

**Comment by inolen** [comment]
Yes, I think I just have to add imgui.cc / microprofile.cc to the static makefile and all should be good, right?

**Comment by twinaphex** [comment]
Yes, that ought to be enough.

**Comment by inolen** [comment]
Is it a problem for this to get checked in as Makefile.retro / Makefile.libretro?

**Comment by twinaphex** [comment]
OK, just a name change? Yes, fine with me.

**Comment by inolen** [comment]
Added the makefile as `Makefile.retro` and added the two cpp files at https://github.com/inolen/redream/blob/master/Makefile.retro#L94.

**Pull request closed without merging**
