### PR TITLE
(libretro) Fix Makefile

### PR DESCRIPTION
**Pull request by orbea**
Fixes the libretro Makefile.

### CODE REVIEW

**Comment by inolen** [comment]
Was something changed with the RA buildbots or something that makes this required?

**Comment by orbea** [comment]
I don't run the buildbot so I'm not sure. I just tried to run the Makefile manually and found it did not work because it was moved from the base directory to deps/libretro while the paths where not updated.

**Comment by twinaphex** [comment]
I think it should be safe to merge this.

**Comment by inolen** [comment]
@twinaphex whatever works for you guys. I believe the current makefile works assuming you're calling it from the project root, with `make -f deps/libretro/Makefile`.

This would mean calling it from `deps/libretro`. I don't mind either way, but I believe that would  mean updating your buildbot.

**Comment by twinaphex** [comment]
Yeah, I think that would become hairy. 

In retrospect, might not be such a good idea to merge it then since it could actually cause compilation to fail right now on the buildbot. The user will just have to know manually which dir to compile it from locally I guess.

**Comment by orbea** [comment]
I would build it like: `make -C deps/libretro` or even 'cd deps/libretro ; make`. Surely there has to be a way for these to all work. I'll look at it in more detail tomorrow.

**Comment by orbea** [comment]
I have updated the commit, I can now confirm that the following three work.
```
make -f deps/libretro/Makefile
make -C deps/libretro
cd deps/libretro ; make
```
My main concern is I am not sure how portable this is? @inolen and @twinaphex could you review this change you have a chance?

**Comment by inolen** [comment]
Was there a consensus on this?

**Comment by orbea** [comment]
I haven't heard anything. I only have linux so I would hesitate to merge something that might not be portable unless someone would be kind enough to test other platforms?

**Pull request closed without merging**
