### PR TITLE
avoid having an empty struct in c

### PR DESCRIPTION
**Pull request by mdeguzis**
* Fixes ##98
* Thanks inolen!

### CODE REVIEW

**Comment by inolen** [comment]
Thanks!

**Comment by inolen** [comment]
Hey @mdeguzis, I've just got around to getting an individual CLA for the project setup at https://cla-assistant.io/inolen/redream. All futures PRs will automatically check if the user has signed this, but I'm manually trying to get retroactive signatures. If you aren't able to fill out the CLA, please let me know so I can remove the contribution.

**Comment by mdeguzis** [comment]
Signed :)

**Comment by inolen** [comment]
@mdeguzis do you happen to have an e-mail I could reach you at? I tried the form on your site but think it may have not went through.

**Comment by mdeguzis** [comment]
I try not to advertise it, maybe it was missed, since I am on an Apache mailing list, so maybe it was mixed in. Try again, with a title "From inolen about redream"

**Comment by inolen** [comment]
Done, thanks!

**Comment by mdeguzis** [comment]
Responded and done :P

**Pull request merged**
